### ISSUE TITLE
ModuleNotFoundError: No module named 'apt_pkg'

### ISSUE THREAD

**Issue by yurydev1** [bootandy/dust#186]
Getting error on first run on ubuntu 20.04
```
[root@host2 ~/dust-v0.7.5-x86_64-unknown-linux-gnu]$ dust -d 1
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

**Comment by yurydev1** [comment]
Sorry, ignore, looks like an issue with the host itself rather than with the dust

**Comment by yurydev1** [comment]
closing the issue
